build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"

    - PYTHON: "C:\\Python35"


init:
  - "ECHO %PYTHON%"

install:
  - "%PYTHON%/Scripts/pip.exe install tox"

test_script:
  - "%PYTHON%/Scripts/tox"
