build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27" 
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"


init:
  - "ECHO %PYTHON%"

install:
  - "%PYTHON%/Scripts/pip.exe install -U pip"
  - "%PYTHON%/Scripts/pip.exe install tox"

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"
